# Generated by Django 4.2.7 on 2026-05-03 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_carmodel_dealer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
